[storage]
driver = "overlay"
runroot = "$XDG_RUNTIME_DIR/bootsybox-nested-containers/runroot"
graphroot = "$HOME/.local/share/bootsybox/nested-containers/storage"

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
