FROM quay.io/fedora/fedora-toolbox:44

ARG BOOTSYBOX_IMAGE_VERSION=development
ARG BOOTSYBOX_IMAGE_REVISION=unknown
ARG BOOTSYBOX_DESKTOP_API=1
ARG BOOTSYBOX_DESKTOP_HOST_API=1

RUN dnf -y --setopt=install_weak_deps=False install \
        niri \
        waybar \
        alacritty \
        fuzzel \
        mako \
        swaylock \
        swaybg \
        xwayland-satellite \
        xdg-desktop-portal \
        xdg-desktop-portal-gtk \
        xdg-desktop-portal-gnome \
        gnome-keyring \
        flatpak \
        distrobox \
        podman \
        fuse-overlayfs \
        mesa-dri-drivers \
        mesa-vulkan-drivers \
        dbus-daemon \
        fuse3 \
        socat \
    && dnf clean all

# Fedora ships niri's maintained default as documentation. Install it as the
# system fallback so a brand-new user gets Waybar plus terminal/launcher/logout
# bindings without first creating a home configuration.
RUN install -D -m 0644 \
        /usr/share/doc/niri/default-config.kdl \
        /etc/niri/config.kdl

COPY desktop/files/usr/local/bin/bootsybox-container-init /usr/local/bin/bootsybox-container-init
COPY desktop/files/usr/local/bin/bootsybox-session /usr/local/bin/bootsybox-session
COPY desktop/files/etc/containers/storage-nested.conf /etc/containers/storage-nested.conf
COPY files/usr/local/bin/bootsybox /usr/local/bin/bootsybox

RUN chmod 0755 \
        /usr/local/bin/bootsybox-container-init \
        /usr/local/bin/bootsybox-session \
        /usr/local/bin/bootsybox \
    && chmod 4755 \
        /usr/bin/newuidmap \
        /usr/bin/newgidmap

LABEL org.opencontainers.image.title="Bootsybox desktop" \
      org.opencontainers.image.description="Reproducible rootless niri desktop for Bootsybox" \
      org.opencontainers.image.source="https://github.com/eelcoh/bootsybox" \
      org.opencontainers.image.version="$BOOTSYBOX_IMAGE_VERSION" \
      org.opencontainers.image.revision="$BOOTSYBOX_IMAGE_REVISION" \
      io.bootsybox.desktop.api="$BOOTSYBOX_DESKTOP_API" \
      io.bootsybox.desktop.host-api="$BOOTSYBOX_DESKTOP_HOST_API"

ENTRYPOINT ["/usr/local/bin/bootsybox-container-init"]
